///<author>dev@bassetti.fr</author>
///<summary>Unit loading / unloading the dll named "TxHtml". This file is generated by TXUtils. Do not modify.</summary>
unit U_Abstract_TxHtml;
interface

uses
  SysUtils,Windows,Contnrs,Classes,U_Abstract,U_Small_Lib;

type
  {$REGION 'U_Main_TxHtml'}
  ///<summary>Base errcor class for the API_HMTL errors.</summary>
  ETxHtml=class(Exception);

  EEndOfTagNotFound=class(ETxHtml);

  EModelApplicationNotFound=class(ETxHtml);

  TTabToHtmlFile=function(AIdObject: Integer; AIdTab: Integer; ADisplaySources: Boolean; ADisplayInformations: Boolean; APortal: Boolean): string; stdcall;

  TTabToHtml=function(AIdObject: Integer; AIdTab: Integer; ADisplaySources: Boolean; ADisplayInformations: Boolean): string; stdcall;

  ///<summary>Fonction renvoyant le numero de revision (build) de l'API_HTML.</summary>
  TGet_Revision_TxHTML=function: Integer; stdcall;

  TObjectPropertiesToHtml=function(const AIdObject: Integer): string; stdcall;
  {$ENDREGION}

  {$REGION 'U_Statistics'}
  TStatisticsToHTMLFile=function(AID_Attribute: Integer; APath_File_Picture: string; AText: string): string; stdcall;

  TCorrelationToHTMLFile=function(APath_File_Picture: string; AText: string): string; stdcall;
  {$ENDREGION}



var
  {$REGION 'U_Main_TxHtml'}
  TabToHtmlFile: TTabToHtmlFile;
  TabToHtml: TTabToHtml;
  Get_Revision_TxHTML: TGet_Revision_TxHTML;
  ObjectPropertiesToHtml: TObjectPropertiesToHtml;
  {$ENDREGION}

  {$REGION 'U_Statistics'}
  StatisticsToHTMLFile: TStatisticsToHTMLFile;
  CorrelationToHTMLFile: TCorrelationToHTMLFile;
  {$ENDREGION}


///<summary>Procedure loading the dll named "TxHtml".</summary>
///<param name="AFilePath">The absolute path to the dll.</param>
procedure Load_TxHtml(AFilePath: string);

///<summary>Procedure unloading the dll named "TxHtml".</summary>
procedure Unload_TxHtml;

///<summary>Function returning true if the dll "TxHtml" was loaded.</summary>
function Get_Dll_TxHtml_Loaded: boolean;

implementation

var
  hDll: THandle;

procedure Load_TxHtml(AFilePath: string);
resourcestring
  RS_Error_Invalide_File='Le fichier %s n''est pas valide.';
begin
  if hDll <> 0 then
    exit;

  Check_FileExists(AFilePath);

  hDll := Load_Dll(AFilePath);

  {$REGION 'U_Main_TxHtml'}
  @TabToHtmlFile := Get_Dll_Function_Adress(hDll,'TabToHtmlFile',AFilePath);
  @TabToHtml := Get_Dll_Function_Adress(hDll,'TabToHtml',AFilePath);
  @Get_Revision_TxHTML := Get_Dll_Function_Adress(hDll,'Get_Revision_TxHTML',AFilePath);
  @ObjectPropertiesToHtml := Get_Dll_Function_Adress(hDll,'ObjectPropertiesToHtml',AFilePath);
  {$ENDREGION}

  {$REGION 'U_Statistics'}
  @StatisticsToHTMLFile := Get_Dll_Function_Adress(hDll,'StatisticsToHTMLFile',AFilePath);
  @CorrelationToHTMLFile := Get_Dll_Function_Adress(hDll,'CorrelationToHTMLFile',AFilePath);
  {$ENDREGION}


end;

procedure Unload_TxHtml;
begin
  if hDll <> 0 then
  begin
    try
      FreeLibrary(hDll);
      hDll := 0;
    except
    end;
  end;
end;

function Get_Dll_TxHtml_Loaded: boolean;
begin
  result := (hDll>0)
end;

initialization
  hDll := 0;

finalization
  Unload_TxHtml;

end.