///<author>dev@bassetti.fr</author>
///<summary>Unit loading / unloading the dll named "Cipher". This file is generated by TXUtils. Do not modify.</summary>
unit U_Abstract_Cipher;
interface

uses
  SysUtils,Windows,U_Small_Lib;

type
  {$REGION 'U_Main_Cipher'}
  TCipher_Type=(
    ctUndefined,
    ctXOR,
    ctRinjdael);

  TEncrypt_Rijndael=function(S: string; AKey: string): string; stdcall;

  TDecrypt_Rijndael=function(S: string; AKey: string): string; stdcall;
  {$ENDREGION}

  {$REGION 'U_XOR'}
  TApply_XOR=function(S: string; AKey: Integer): string; stdcall;
  {$ENDREGION}

var
  {$REGION 'U_Main_Cipher'}
  Encrypt_Rijndael: TEncrypt_Rijndael;
  Decrypt_Rijndael: TDecrypt_Rijndael;
  {$ENDREGION}

  {$REGION 'U_XOR'}
  Apply_XOR: TApply_XOR;
  {$ENDREGION}


///<summary>Procedure loading the dll named "Cipher".
///<param name="APath_File_DLL">The absolute path to the dll.</param>
procedure Load_Cipher(APath_File_DLL: string);

///<summary>Procedure unloading the dll named "Cipher".</summary>
procedure Unload_Cipher;

///<summary>Function returning true if the dll "Cipher" was loaded.</summary>
function Get_Dll_Cipher_Loaded: boolean;

implementation

var
  hDll: THandle;

procedure Load_Cipher(APath_File_DLL: string);
resourcestring
  RS_Error_Invalide_File='Le fichier %s n''est pas valide.';
begin
  if hDll <> 0 then
    exit;

  Check_FileExists(APath_File_DLL);

  hDll := Load_Dll(APath_File_DLL);

  {$REGION 'U_Main_Cipher'}
  @Encrypt_Rijndael := Get_Dll_Function_Adress(hDll,'Encrypt_Rijndael',APath_File_DLL);
  @Decrypt_Rijndael := Get_Dll_Function_Adress(hDll,'Decrypt_Rijndael',APath_File_DLL);
  {$ENDREGION}

  {$REGION 'U_XOR'}
  @Apply_XOR := Get_Dll_Function_Adress(hDll,'Apply_XOR',APath_File_DLL);
  {$ENDREGION}


end;

procedure Unload_Cipher;
begin
  if hDll <> 0 then
  begin
    try
      FreeLibrary(hDll);
      hDll := 0;
    except
    end;
  end;
end;

function Get_Dll_Cipher_Loaded: boolean;
begin
  result := (hDll>0)
end;

initialization
  hDll := 0;

finalization
  Unload_Cipher;

end.